export const metadata = { title: "Disclaimer — JARVIS Trader" };

export default function DisclaimerPage() {
  return (
    <article className="prose prose-invert prose-sm max-w-none">
      <h1 className="text-2xl font-bold text-white">Disclaimer</h1>
      <p className="text-muted-foreground text-sm">Last updated: March 2026</p>

      <h2 className="text-lg font-semibold text-white mt-8">No Financial Advice</h2>
      <p className="text-muted-foreground">
        JARVIS Trader is a <strong className="text-white">research and educational tool</strong>.
        Nothing on this platform constitutes financial advice, investment advice, trading advice,
        or any other form of professional advice. All signals, scores, regime classifications,
        and strategy outputs are generated by machine learning models for informational purposes only.
      </p>

      <h2 className="text-lg font-semibold text-white mt-8">Paper Trading = Simulation</h2>
      <p className="text-muted-foreground">
        All trading on JARVIS Trader is <strong className="text-white">simulated (paper trading)</strong>.
        No real money is at risk. Simulated results do not represent actual trading and may not
        reflect the impact of real market conditions such as slippage, liquidity, and execution delays.
      </p>

      <h2 className="text-lg font-semibold text-white mt-8">No Guarantee of Accuracy</h2>
      <p className="text-muted-foreground">
        While our ML models are rigorously tested (8,890+ tests, 96%+ code coverage), predictions
        about financial markets are inherently uncertain. Past model performance does not guarantee
        future results. OOD (Out-of-Distribution) warnings indicate when the model encounters
        unfamiliar conditions — but absence of a warning does not guarantee accuracy.
      </p>

      <h2 className="text-lg font-semibold text-white mt-8">Risk Warning</h2>
      <p className="text-muted-foreground">
        Trading financial instruments carries a high level of risk and may not be suitable for all
        investors. You should carefully consider your investment objectives, level of experience,
        and risk appetite. Never invest money you cannot afford to lose. If you decide to trade
        real assets based on insights from this platform, you do so at your own risk.
      </p>

      <h2 className="text-lg font-semibold text-white mt-8">Third-Party Data</h2>
      <p className="text-muted-foreground">
        Market data is provided by third-party services (Binance, Alpha Vantage, etc.).
        We do not guarantee the accuracy, completeness, or timeliness of third-party data.
      </p>
    </article>
  );
}
